<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/player/css/player.css">
    <link rel="shortcut icon" href="/static/images/icon.png" type="image/png">
    <link rel="stylesheet" href="/static/node_modules/boxicons/css/boxicons.min.css">
    <link rel="manifest" href="/manifest.json" />
    <link rel="apple-touch-icon" href="/static/images/icons/icon-512x512.png" />
    <meta name="apple-mobile-web-app-status-bar" content="#13b522" />
    <meta name="theme-color" content="#13b522" />
    <title>Жабблер</title>
</head>
<body>
    <div id="app">
        <div class="dFaIcjSc" style="height:100vh;text-align:center;cursor:pointer;" onclick="window.location.href = '/';">
            <div>
                <h1>
                    404
                </h1>
                <div>
                    <span>
                        The page you looking for isn't here.
                    </span>
                </div>
            </div>
        </div>
        <preloader src="/static/js/new_messenger.js"></preloader>
        <preloader src="/static/player/js/zhabblerplayer.js"></preloader>
    </div>
    <script src="/static/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="/static/node_modules/jquery-ui/dist/jquery-ui.min.js"></script>
    <script src="/static/js/main.js"></script>
</body>
</html>